[package]
name = "cloud-checksum"
description = "A tool to calculate multiple checksums concurrently locally and in the cloud."
version = "0.1.0"
license.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
clap = { version = "4", features = ["derive", "env"] }
thiserror = "1"

tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "io-util", "io-std", "fs"] }
futures-util = "0.3"

md5 = "0.7"
sha1 = "0.10"
sha2 = "0.10"

# Value parsing
humantime = "2"
