name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
#  test:
#    runs-on: ubuntu-latest
#    env:
#      CARGO_INCREMENTAL: 0
#      SCCACHE_GHA_ENABLED: "true"
#      RUSTC_WRAPPER: "sccache"
#    steps:
#      - name: Cache
#        uses: mozilla-actions/sccache-action@v0.0.8
#      - name: Check out
#        uses: actions/checkout@v4
#      - name: Install Rust
#        uses: dtolnay/rust-toolchain@master
#        with:
#          toolchain: stable
#          components: rustfmt, clippy
#      - name: Cargo fmt
#        run: cargo fmt --all -- --check
#      - name: Cargo clippy
#        run: cargo clippy --all-targets --all-features  -- -D warnings
#      - name: Run cargo tests
#        if: always()
#        run: cargo test --all-features -- --nocapture
#      - name: Run md5
#        if: always()
#        run: md5sum data/test_file && sha1sum data/test_file && sha256sum data/test_file
